# Generated by Django 5.1.7 on 2025-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_mask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
