# Generated by Django 5.1.7 on 2025-04-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_mask', '0002_alter_pharmacy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('color', models.TextField()),
                ('num_per_pack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('cash_balance', models.FloatField()),
                ('mon_open', models.TextField(blank=True, null=True)),
                ('mon_close', models.TextField(blank=True, null=True)),
                ('tue_open', models.TextField(blank=True, null=True)),
                ('tue_close', models.TextField(blank=True, null=True)),
                ('wed_open', models.TextField(blank=True, null=True)),
                ('wed_close', models.TextField(blank=True, null=True)),
                ('thu_open', models.TextField(blank=True, null=True)),
                ('thu_close', models.TextField(blank=True, null=True)),
                ('fri_open', models.TextField(blank=True, null=True)),
                ('fri_close', models.TextField(blank=True, null=True)),
                ('sat_open', models.TextField(blank=True, null=True)),
                ('sat_close', models.TextField(blank=True, null=True)),
                ('sun_open', models.TextField(blank=True, null=True)),
                ('sun_close', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyMasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phantom_mask.masks')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phantom_mask.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.TextField()),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phantom_mask.masks')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phantom_mask.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cash_balance', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phantom_mask.users'),
        ),
    ]
