# Generated by Django 5.1.7 on 2025-04-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_mask', '0004_alter_masks_options_alter_pharmacies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masks',
            table='masks',
        ),
        migrations.AlterModelTable(
            name='pharmacies',
            table='pharmacies',
        ),
        migrations.AlterModelTable(
            name='pharmacymasks',
            table='pharmacy_masks',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
