# Generated by Django 5.1.7 on 2025-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_mask', '0005_alter_masks_table_alter_pharmacies_table_and_more'),
    ]

    operations = [
    ]
