# Generated by Django 5.1.7 on 2025-04-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_mask', '0007_auto_20250404_0325'),
    ]

    operations = [
    ]
